In [26]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [28]:
#verisetini okuyoruz
df=pd.read_csv("Puanlar.csv")
df2=df.copy()

In [29]:
df.head()

ID                    Bolum                          Universite      Sehir  \
0   0  Bilgisayar Mühendisligi  ANADOLU ÜNİVERSİTESİ (ESKİŞEHİR)-İ  Eskişehir   
1   1  Bilgisayar Mühendisligi                 ANKARA ÜNİVERSİTESİ     Ankara   
2   2  Bilgisayar Mühendisligi        ATILIM UNİVERSİTESİ (ANKARA)     Ankara   
3   3  Bilgisayar Mühendisligi      ATILIM UNİVERSİTESİ (ANKARA)-B     Ankara   
4   4  Bilgisayar Mühendisligi    ATILIM UNİVERSİTESİ (ANKARA)-B50     Ankara   

      1999     2000  2001  2002     2003     2004     2005     2006     2007  \
0    0.000    0.000   0.0   0.0  350.781  349.184  351.886  331.568  346.516   
1    0.000    0.000   0.0   0.0  352.496  354.072  356.375  337.520  350.939   
2  172.266  170.072   0.0   0.0  252.992  279.343  296.337  296.337  272.082   
3    0.000    0.000   0.0   0.0  340.244  339.154  345.326  315.555  335.198   
4    0.000    0.000   0.0   0.0    0.000    0.000  334.631  295.837  316.256   

      2008   2009     2010  
0  338.689  452.0  476.512  
1  342.315  458.0  487.446  
2  253.769    0.0    0.000  
3  328.233  437.0  459.950  
4  308.373  334.0  382.086

### Veri setinde bölüm, üniversite ve kayıt sayıları aşağıda listelenmiştir.

In [30]:
df['ID'].value_counts()

140    1
43     1
49     1
48     1
47     1
      ..
99     1
100    1
101    1
102    1
0      1
Name: ID, Length: 141, dtype: int64

In [31]:
df['Universite'].value_counts()

EGE ÜNİVERSİTESİ (İZMİR)               2
HACETTEPE ÜNİVERSİTESİ (ANKARA)        2
BAŞKENT  ÜNİVERSİTESİ (ANKARA)         2
BAŞKENT  ÜNİVERSİTESİ (ANKARA)-B       2
YEDİTEPE  ÜNİVERSİTESİ (İSTANBUL)      2
                                      ..
İSTANBUL KÜLTÜR  ÜNİVERSİTESİ-İ-B      1
HARRAN ÜNİVERSİTESİ (fiANLIURFA)       1
MALTEPE  ÜNİVERSİTESİ (İSTANBUL)       1
BEYKENT ÜNİVERSİTESİ (İSTANBUL)        1
ONDOKUZ MAYIS ÜNİVERSİTESİ (SAMSUN)    1
Name: Universite, Length: 131, dtype: int64

In [32]:
df['Bolum'].value_counts()

Bilgisayar Mühendisligi    85
Tıp Fakültesi              56
Name: Bolum, dtype: int64

In [33]:
df['Sehir'].value_counts()

İstanbul         46
Ankara           25
Kktc              9
İzmir             9
Kocaeli           4
Eskişehir         3
Konya             3
Sakarya           2
Adana             2
Isparta           2
Kayseri           2
Denizli           2
Şanlıurfa         2
Mersin            2
Çanakkale         2
Elazığ            2
Trabzon           2
Edirne            2
Kütahya           1
Aydın             1
Zonguldak         1
Bursa             1
Düzce             1
Van               1
KARS              1
Antalya           1
Tokat             1
Malatya           1
Kahramanmaraş     1
Samsun            1
Kırıkkale         1
Manisa            1
Gaziantep         1
Diyarbakır        1
Bolu              1
Erzurum           1
Afyon             1
Sivas             1
Name: Sehir, dtype: int64

## Eksik Veri Kontrolü

Veri setimiz aşağıda kontrol edilmiş ve sütunlarda eksik veri bulunmamaktadır.

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          141 non-null    int64  
 1   Bolum       141 non-null    object 
 2   Universite  141 non-null    object 
 3   Sehir       141 non-null    object 
 4   1999        141 non-null    float64
 5   2000        141 non-null    float64
 6   2001        141 non-null    float64
 7   2002        141 non-null    float64
 8   2003        141 non-null    float64
 9   2004        141 non-null    float64
 10  2005        141 non-null    float64
 11  2006        141 non-null    float64
 12  2007        141 non-null    float64
 13  2008        141 non-null    float64
 14  2009        141 non-null    float64
 15  2010        141 non-null    float64
dtypes: float64(12), int64(1), object(3)
memory usage: 17.8+ KB


In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [36]:
X = df[['1999', '2000','2001', '2002', '2003', '2004', '2005','2006','2007']] .values
y = df['2010'].values

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [38]:
print(X_train)  
print(y_train)

[[  0.      0.      0.      0.    368.227 369.692 370.648 359.295 365.892]
 [  0.      0.      0.      0.    366.651 370.275 373.07  365.822 371.574]
 [  0.      0.      0.      0.    348.078 349.714 354.61  339.431 353.517]
 [  0.      0.      0.      0.      0.      0.      0.    311.429   0.   ]
 [  0.      0.      0.      0.    284.319 310.617 318.932 274.17  297.601]
 [  0.      0.      0.      0.    350.991 350.75  353.589 334.217 348.656]
 [  0.    209.187 211.741   0.    357.635 359.836 364.242 353.436 362.902]
 [  0.      0.      0.      0.      0.      0.    263.379 263.379 297.907]
 [  0.      0.      0.      0.    335.273 342.215 348.778 330.819 348.586]
 [  0.      0.      0.      0.      0.      0.    334.73  303.215 323.825]
 [  0.      0.      0.      0.    351.403 352.651 357.401 343.301 356.008]
 [  0.      0.      0.      0.    348.718 350.851 356.232 341.681 355.225]
 [  0.      0.      0.      0.    350.321 350.475 352.48  325.734 343.608]
 [170.884 178.028 176.121

## Lineer Regresyon (Sklearn)

In [39]:
#L_Reg=LinearRegression()
L_Reg = LinearRegression().fit(X_train, y_train)
L_Reg.score(X,y)

0.4558686375321833

## Lineer Regresyon (Sklearn Kütüphanesi Kullanmadan)

In [40]:
#Burada csv dosyasını okuduğumuz df değişkenini kullanmak üzere puanlar değişkenine atıyoruz.
puanlar = df
colums = (puanlar.columns[0])
puanlar.head()

ID                    Bolum                          Universite      Sehir  \
0   0  Bilgisayar Mühendisligi  ANADOLU ÜNİVERSİTESİ (ESKİŞEHİR)-İ  Eskişehir   
1   1  Bilgisayar Mühendisligi                 ANKARA ÜNİVERSİTESİ     Ankara   
2   2  Bilgisayar Mühendisligi        ATILIM UNİVERSİTESİ (ANKARA)     Ankara   
3   3  Bilgisayar Mühendisligi      ATILIM UNİVERSİTESİ (ANKARA)-B     Ankara   
4   4  Bilgisayar Mühendisligi    ATILIM UNİVERSİTESİ (ANKARA)-B50     Ankara   

      1999     2000  2001  2002     2003     2004     2005     2006     2007  \
0    0.000    0.000   0.0   0.0  350.781  349.184  351.886  331.568  346.516   
1    0.000    0.000   0.0   0.0  352.496  354.072  356.375  337.520  350.939   
2  172.266  170.072   0.0   0.0  252.992  279.343  296.337  296.337  272.082   
3    0.000    0.000   0.0   0.0  340.244  339.154  345.326  315.555  335.198   
4    0.000    0.000   0.0   0.0    0.000    0.000  334.631  295.837  316.256   

      2008   2009     2010  
0  338.689  452.0  476.512  
1  342.315  458.0  487.446  
2  253.769    0.0    0.000  
3  328.233  437.0  459.950  
4  308.373  334.0  382.086

In [41]:
#Tahminde bulunmak üzere puanlar dışında ki değerleri kaldırıyoruz.
del puanlar['ID']
del puanlar['Bolum']
del puanlar['Universite']
del puanlar['Sehir']

In [42]:
#Sonraki aşamalarda normalizasyon yapılacağı için orjinal değerleri yazdırabilmek adına puanlari tmp değişkeninde tutuyoruz.
tmpPuan=puanlar.copy()

In [43]:
#max ve min değerlerini tutuyoruz.
max= [puanlar[c].max() for c in puanlar.columns] 
min= [puanlar[c].min() for c in puanlar.columns]

In [44]:
#Normalizasyon işlemi uyguluyoruz.
i=0
for c in puanlar.columns:
    while(i<len(puanlar.columns)): 
        puanlar[c]=(puanlar[c]-min[i])/(max[i]-min[i])
        i=i+1
        break

In [45]:
#Son 3 yılı tahminde bulunmak için veriyi bölüyoruz.
array = puanlar.values
x_train=[]
yil10=[]
yil09=[]
yil08=[]
a=puanlar.shape
for i in range(a[0]):                      
    x_train.append((array[i][:-3]).tolist())
    yil08.append(array[i][-1])
    yil09.append(array[i][-2])
    yil10.append(array[i][-3])

In [46]:
#x_train için katsayılar matrisi hesaplıyoruz.
m=np.ones((141,1)) #Toplam kayıt sayısı 141'dir.
b=np.matrix(x_train)
b=np.concatenate((m,b),axis=1)     
d=b.T
e=np.linalg.inv(np.matmul(d,b))
yil10=np.matrix(yil10)
yil10=yil10.T
yil09=np.matrix(yil09)
yil09=yil09.T
yil08=np.matrix(yil08)
yil08=yil08.T
f=np.matmul(e,d)
c1=np.matmul(f,yil10)
c2=np.matmul(f,yil09)
c3=np.matmul(f,yil08)

In [52]:
#Burada test verilerini alıyoruz.(199-2008 arası değerler toplam 9 adet)Ardından tahminde bulunarak saklıyoruz.
x_test=[[1],]
id=[int(input("Tahminde bulunmak istediğiniz üniversite için ID giriniz :"))]

for j in range(9):
    print(float(tmpPuan.iloc[id,j]))
    x_test.append([float(tmpPuan.iloc[id,j])])

for i in range(9):
    x_test[i+1][0]=(x_test[i+1][0]-min[i])/(max[i]-min[i])
x_test=np.matrix(x_test)
yil10=np.matmul(c1.T,x_test)
yil09=np.matmul(c2.T,x_test)
yil08=np.matmul(c3.T,x_test)

Tahminde bulunmak istediğiniz üniversite için ID giriniz :91
198.516
199.305
197.52200000000002
200.424
345.185
348.04
353.37199999999996
336.283
351.236


In [53]:
#Burada da normalizasyon işlemi geri alınarak tahmin yazdırılır ve gerçek değerler ile karşılaştırılır.
print("İlgili ID'ye ait üniversite :", str(df2.iloc[id,2]), "\nBölüm :", str(df2.iloc[id,1]))
print("2010 tahmini:",(yil10*(max[-1]-min[-1]))+min[-1], "Gerçek Değer: ", float(tmpPuan.iloc[id,11]))
print("2009 tahmini:",(yil09*(max[-2]-min[-2]))+min[-2], "Gerçek Değer: ", float(tmpPuan.iloc[id,10]))
print("2008 tahmini:",(yil08*(max[-1]-min[-1]))+min[-1], "Gerçek Değer: ", float(tmpPuan.iloc[id,9]))

İlgili ID'ye ait üniversite : 91    BAŞKENT  ÜNİVERSİTESİ (ANKARA)
Name: Universite, dtype: object 
Bölüm : 91    Tıp Fakültesi
Name: Bolum, dtype: object
2010 tahmini: [[512.34564358]] Gerçek Değer:  507.69300000000004
2009 tahmini: [[366.46740025]] Gerçek Değer:  473.0
2008 tahmini: [[330.39503267]] Gerçek Değer:  342.913
